default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30 

development:
  <<: *default
  database: collector_development
test:
  <<: *default
  database: collector_test
production:
  <<: *default
  database: collector_production
  username: collector
  password: <%= ENV['COPIERPH_DATABASE_PASSWORD'] %>
